from typing import Protocol, Any

class DatabaseSessionInterface(Protocol):
    def fetch_one(self, query: str, params: dict) -> Any: ...
    def fetch_all(self, query: str, params: dict) -> list[Any]: ...
    def execute(self, query: str, params: dict) -> None: ...
